
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEN = 29;
  public static final int SEMICOL = 39;
  public static final int IDENTIFIER = 52;
  public static final int ARROW = 70;
  public static final int LCURLY = 34;
  public static final int BADCHAR = 62;
  public static final int READ = 23;
  public static final int TOP = 9;
  public static final int FDEF = 15;
  public static final int DICT = 5;
  public static final int COMMA = 56;
  public static final int ELIF = 19;
  public static final int RPAREN = 60;
  public static final int FI = 28;
  public static final int LPAREN = 59;
  public static final int INTERSECTION = 65;
  public static final int FALSE = 13;
  public static final int NOT = 45;
  public static final int FLOAT = 8;
  public static final int THEN = 57;
  public static final int POSINTEGER = 72;
  public static final int KCHAR = 4;
  public static final int CHARACTER = 53;
  public static final int KRAT = 55;
  public static final int ISEQUAL = 32;
  public static final int LESSTHAN = 44;
  public static final int ALIAS = 17;
  public static final int ZERO = 73;
  public static final int TRUE = 12;
  public static final int LESSEQUAL = 30;
  public static final int PLUS = 40;
  public static final int FORALL = 21;
  public static final int WHILE = 22;
  public static final int UNION = 64;
  public static final int EQUAL = 38;
  public static final int TDEF = 14;
  public static final int DCOLON = 50;
  public static final int RSQUARE = 37;
  public static final int DO = 27;
  public static final int VOID = 16;
  public static final int DIV = 43;
  public static final int MOREEQUAL = 31;
  public static final int KINT = 6;
  public static final int RETURN = 25;
  public static final int MULT = 42;
  public static final int THREAD = 67;
  public static final int ELSE = 20;
  public static final int MORETHAN = 49;
  public static final int BREAK = 71;
  public static final int DOT = 61;
  public static final int POWER = 48;
  public static final int LAMBDAX = 69;
  public static final int EOF = 0;
  public static final int LSQUARE = 36;
  public static final int PRINT = 24;
  public static final int RATIONAL = 7;
  public static final int MAIN = 2;
  public static final int MINUS = 41;
  public static final int IN = 11;
  public static final int DIFFERENCE = 66;
  public static final int OR = 47;
  public static final int SET = 63;
  public static final int error = 1;
  public static final int SEQ = 10;
  public static final int IF = 18;
  public static final int COLON = 51;
  public static final int OD = 26;
  public static final int NOTEQUAL = 33;
  public static final int KBOOL = 3;
  public static final int STRING = 58;
  public static final int AND = 46;
  public static final int WAIT = 68;
  public static final int RCURLY = 35;
  public static final int KFLOAT = 54;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "KBOOL",
  "KCHAR",
  "DICT",
  "KINT",
  "RATIONAL",
  "FLOAT",
  "TOP",
  "SEQ",
  "IN",
  "TRUE",
  "FALSE",
  "TDEF",
  "FDEF",
  "VOID",
  "ALIAS",
  "IF",
  "ELIF",
  "ELSE",
  "FORALL",
  "WHILE",
  "READ",
  "PRINT",
  "RETURN",
  "OD",
  "DO",
  "FI",
  "LEN",
  "LESSEQUAL",
  "MOREEQUAL",
  "ISEQUAL",
  "NOTEQUAL",
  "LCURLY",
  "RCURLY",
  "LSQUARE",
  "RSQUARE",
  "EQUAL",
  "SEMICOL",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "LESSTHAN",
  "NOT",
  "AND",
  "OR",
  "POWER",
  "MORETHAN",
  "DCOLON",
  "COLON",
  "IDENTIFIER",
  "CHARACTER",
  "KFLOAT",
  "KRAT",
  "COMMA",
  "THEN",
  "STRING",
  "LPAREN",
  "RPAREN",
  "DOT",
  "BADCHAR",
  "SET",
  "UNION",
  "INTERSECTION",
  "DIFFERENCE",
  "THREAD",
  "WAIT",
  "LAMBDAX",
  "ARROW",
  "BREAK",
  "POSINTEGER",
  "ZERO"
  };
}

